export const NAVIGATION_BOTTOM_TAB = 'NAVIGATION_BOTTOM_TAB';
export const NAVIGATION_MAIN_APP = 'NAVIGATION_MAIN_APP';
export const NAVIGATION_TAB_HOME = 'NAVIGATION_TAB_HOME';
export const NAVIGATION_TAB_EXAMPLE1 = 'NAVIGATION_TAB_EXAMPLE1';
export const NAVIGATION_TAB_EXAMPLE2 = 'NAVIGATION_TAB_EXAMPLE2';
export const NAVIGATION_TAB_EXAMPLE3 = 'NAVIGATION_TAB_EXAMPLE3';


//

export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_EXAMPLE1 = 'ROUTE_EXAMPLE1';
export const ROUTE_EXAMPLE2 = 'ROUTE_EXAMPLE2';
export const ROUTE_EXAMPLE3 = 'ROUTE_EXAMPLE3';
